### PR TITLE
Add trace snippets

### PR DESCRIPTION
**Pull request by hschafer**

### CODE REVIEW

**Comment by hschafer** [comment]
Two bugs:

- [ ] Some snippets load as blank (Module 1, Lesson 2: Conditionals)
- [ ] Refreshing a page causes some weird scrolling due to iframe loads?

**Comment by zachkirsch** [comment]
@hschafer those other 3 issues should be fixed!

> change the logic there to show a replay button once they've pressed run?

I did exactly this, let me know what you think.

One thing I noticed is that the "replay" view is pretty squashed at the current heights. It looks better with a constant height around 400px, but that results in the "code" view taking up more space than you might want. Unfortunately, we don't get a lot of control on our end of changing the height dynamically - we're at the whim of the iframe's height.

**Comment by hschafer** [comment]
This looks fantastic! 

Yeah, I was actually thinking about the fact with the limited iframe size and how the trace would look. I was thinking there were two approaches to go with this, but wasn't quite sure which would be better:

1. As you suggested, make all of the code snippets taller. 400px seems reasonable, but still is a little squished if there is a long code cell and/or variables. It might be trying to show too much with a whole replay in a tiny window.
    * Maybe an option 1.5 is to dynamically resize the iframe when they click on it? I don't think I can do any fancier inspection than just focusing on the element, but that might solve the problem of saving space when not in use.
2. Have the run button only show output and there be a button to show replay launch another tab. The benefit of this is they get the whole trace experience in the browser without it feeling crammed in, but has the downside of not having everything on the one page.

I'll consider how to implement option 1.5 to see if it seems feasible from a UX standpoint!

**Comment by zachkirsch** [comment]
Great points/ideas. I think 1.5 is probably the best - a minimal version of the code with a run button that expands when you click run.

One idea of how to do this is that we can change the embed code to be an html/js snippet instead of an iframe. That would give us a lot more control over the sizing rather than just be stuck at the static height of the iframe. This is what codepen does:

Screen Shot 2022-01-17 at 3 03 20 PM


Thoughts?

**Comment by hschafer** [comment]
That's fine by me! I'm a little less familiar with HTML/JS snippets so I might need a reference for where to start!

**Comment by zachkirsch** [comment]
I think all the work can be on our end - side benefit for us is that we can then use the fruits of this iteration for other embed use cases :)

The only work on your end should be to change this iframe https://github.com/cse163/book/blob/de2e8312fe6caf8597b3fb9977c076fb27c956fe/book_source/source/ext/custom_directives.py#L13-L21

to something more like
```html
    <div class="trace-snippet-container">
        <div data-trace-payload="files={params}&language=PYTHON&hideReadonlyFiles=true">
            << FALLBACK SNIPPET >>
        </div>
    </div>
```

A side benefit here is that we can specify a fallback snippet that gets rendered by default. If our script fails to load for whatever reason, then the snippet will still be shown. I remember this is something we had discussed last week.

Final step on your end will be to include a `<script src="https://learnwithtrace.com/some-embed-script.js" />` somewhere on the page. This script will handle the logic of (1) replacing the fallback snippets with the small Trace snippets and (2) changing the height dynamically once the student clicks Run.

All in all, action is on me to figure out how to do this :) Should have something by the end of the week.

**Comment by hschafer** [comment]
That sounds great to me! I can work on the changes on my end to generate the HTML fragment you shared and the fallback being the old code from before!

**Comment by zachkirsch** [comment]
Sounds great!

**Comment by dannysheridan** [comment]
Hunter, ready to merge?

**Comment by hschafer** [comment]
haha almost! 

I was trying to figure out how to keep code highlighting on the default one (but is a little tricky with my setup). Sorry for dropping this, got a bit busy with my classes!

**Comment by dannysheridan** [comment]
Lmk how we can be helpful. Looking forward to showing off the snippets in the book when live.

**Comment by hschafer** [comment]
I guess it was just one of those things I needed a break from to figure out! It was astonishing how quickly I figured it out after not making any progress when I was trying a few weeks back 😄.

Will merge once I do a final check, and I'll email my high school teacher about this!

**Comment by dannysheridan** [comment]
Merged!

The "take a walk" trick but over a few weeks! If the hs teacher would value a live demo of Trace, I'm game to schedule time.

**Pull request merged**
